import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import CartContextProvider, {cartContext} from "./../../src/context/cartContext"
import Footer from "./_components/Footer/Footer";
import WishlistContextProvider from "@/context/wishlistContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider>
          <WishlistContextProvider>
            <MySessionProvider>

            <Navbar></Navbar>
            <div className="flex-grow min-h-[calc(100vh-400px)] container mx-auto px-4 md:px-8 lg:px-12">
              {children}
            </div>
            <Footer />
            <Toaster />
            </MySessionProvider>
          </WishlistContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
